<?php

return [
    'pack_modules' => [
        'weekly_off' => ['weeklyOffManagement'],
        'medical_claims' => ['medicalClaims'],
        'leave_workflow' => ['supervisorLeaveApproval'],
    ],
    'any_pack_modules' => [
        'pendingPayments' => ['medical_claims', 'salary_advance'],
    ],
    'always' => ['dashboard', 'myProfile', 'changePassword'],
    'admin_only' => ['userManagement'],
    'actions' => ['view', 'add', 'edit', 'delete', 'approve'],
    'modules' => [
        ['key' => 'dashboard', 'label' => 'Dashboard', 'group' => 'Core', 'actions' => ['view']],
        ['key' => 'userManagement', 'label' => 'User Management & ACL', 'group' => 'Core', 'actions' => ['view', 'add', 'edit', 'delete']],
        ['key' => 'laborManagement', 'label' => 'Labor Management', 'group' => 'Core', 'actions' => ['view', 'edit']],
        ['key' => 'show', 'label' => 'Show Employee', 'group' => 'HR Master', 'actions' => ['view', 'edit']],
        ['key' => 'employeeMaster', 'label' => 'Add Employee Master', 'group' => 'HR Master', 'actions' => ['view', 'add', 'edit', 'delete']],
        ['key' => 'departmentMaster', 'label' => 'Department Master', 'group' => 'HR Master', 'actions' => ['view', 'add', 'edit', 'delete']],
        ['key' => 'shiftTime', 'label' => 'Shift Time', 'group' => 'HR Master', 'actions' => ['view', 'add', 'edit', 'delete']],
        ['key' => 'grouproster', 'label' => 'Roster', 'group' => 'HR Master', 'actions' => ['view', 'add', 'edit', 'delete']],
        ['key' => 'rosterCalendar', 'label' => 'Roster Calendar', 'group' => 'HR Master', 'actions' => ['view']],
        ['key' => 'shiftOvertimeRates', 'label' => 'Shift OT Rates', 'group' => 'HR Master', 'actions' => ['view', 'edit']],
        ['key' => 'resignation', 'label' => 'Resignation request', 'group' => 'HR Master', 'actions' => ['view', 'add', 'edit', 'delete']],
        ['key' => 'termination', 'label' => 'Resignation approval', 'group' => 'HR Master', 'actions' => ['view', 'add', 'edit', 'delete']],
        ['key' => 'createNewAllowance', 'label' => 'Allowance', 'group' => 'Payroll', 'actions' => ['view', 'add', 'edit', 'delete']],
        ['key' => 'createNewDeduction', 'label' => 'Deduction', 'group' => 'Payroll', 'actions' => ['view', 'add', 'edit', 'delete']],
        ['key' => 'createNewBonus', 'label' => 'Bonus', 'group' => 'Payroll', 'actions' => ['view', 'add', 'edit', 'delete']],
        ['key' => 'dinnerAllowance', 'label' => 'Dinner Allowance', 'group' => 'Payroll', 'actions' => ['view', 'edit', 'approve']],
        ['key' => 'viewLoans', 'label' => 'View Loans', 'group' => 'Payroll', 'actions' => ['view', 'edit', 'delete']],
        ['key' => 'employeeLoan', 'label' => 'Employee Wise Loan', 'group' => 'Payroll', 'actions' => ['view', 'add', 'edit', 'delete']],
        ['key' => 'loanApprovals', 'label' => 'Loan approval', 'group' => 'Payroll', 'actions' => ['view', 'approve']],
        ['key' => 'SalaryProcessPage', 'label' => 'Salary Process', 'group' => 'Payroll', 'actions' => ['view', 'add', 'edit']],
        ['key' => 'SalaryPage', 'label' => 'View Salary', 'group' => 'Payroll', 'actions' => ['view']],
        ['key' => 'TimeCard', 'label' => 'Time Card', 'group' => 'Attendance', 'actions' => ['view', 'add', 'edit', 'delete']],
        ['key' => 'Overtime', 'label' => 'Over Time', 'group' => 'Attendance', 'actions' => ['view', 'add', 'edit', 'delete']],
        ['key' => 'lateEarlyApproval', 'label' => 'Late / Early Approval', 'group' => 'Attendance', 'actions' => ['view', 'approve']],
        ['key' => 'timeCardApproval', 'label' => 'Time Card Approval', 'group' => 'Attendance', 'actions' => ['view', 'approve']],
        ['key' => 'monthlyLateDeduction', 'label' => 'Monthly Late Deduction', 'group' => 'Attendance', 'actions' => ['view', 'edit']],
        ['key' => 'excessLateReview', 'label' => 'Late Over 30 Minutes', 'group' => 'Attendance', 'actions' => ['view', 'edit']],
        ['key' => 'leaveMaster', 'label' => 'Leave Form', 'group' => 'Leave', 'actions' => ['view', 'add', 'edit', 'delete']],
        ['key' => 'leaveApproval', 'label' => 'Leave Approval', 'group' => 'Leave', 'actions' => ['view', 'approve']],
        ['key' => 'supervisorLeaveApproval', 'label' => 'Supervisor Leave Approval', 'group' => 'Leave', 'actions' => ['view', 'approve'], 'pack' => 'leave_workflow'],
        ['key' => 'hrLeaveApproval', 'label' => 'HR Leave Approval', 'group' => 'Leave', 'actions' => ['view', 'approve']],
        ['key' => 'noPayManagement', 'label' => 'NoPay', 'group' => 'Leave', 'actions' => ['view', 'add', 'edit', 'delete']],
        ['key' => 'advanceApprovals', 'label' => 'Advance Approvals', 'group' => 'Benefits', 'actions' => ['view', 'approve']],
        ['key' => 'weeklyOffManagement', 'label' => 'Weekly Offs', 'group' => 'Benefits', 'actions' => ['view', 'approve'], 'pack' => 'weekly_off'],
        ['key' => 'medicalClaims', 'label' => 'Medical Claims', 'group' => 'Benefits', 'actions' => ['view', 'approve'], 'pack' => 'medical_claims'],
        ['key' => 'companyNotices', 'label' => 'Company notices', 'group' => 'Benefits', 'actions' => ['view', 'add', 'delete']],
        ['key' => 'pendingPayments', 'label' => 'Pending Payments', 'group' => 'Benefits', 'actions' => ['view', 'edit']],
        ['key' => 'leavecalendar', 'label' => 'Leave Calendar', 'group' => 'Leave', 'actions' => ['view']],
        ['key' => 'leaveSettings', 'label' => 'Leave Settings', 'group' => 'Settings', 'actions' => ['view', 'edit']],
        ['key' => 'employeeLeaveBalance', 'label' => 'Employee Leave Balances', 'group' => 'Settings', 'actions' => ['view', 'edit']],
        ['key' => 'nopayWorkingDays', 'label' => 'NoPay Working Days', 'group' => 'Settings', 'actions' => ['view', 'edit']],
        ['key' => 'attendanceReport', 'label' => 'Attendance Report', 'group' => 'Reports', 'actions' => ['view']],
        ['key' => 'singleEntryReport', 'label' => 'Single Entry Report', 'group' => 'Reports', 'actions' => ['view']],
        ['key' => 'absentReport', 'label' => 'Absent Report', 'group' => 'Reports', 'actions' => ['view']],
        ['key' => 'shiftHoursReport', 'label' => 'Shift Hours Reports', 'group' => 'Reports', 'actions' => ['view']],
        ['key' => 'monthlyWorkingHoursReport', 'label' => 'Monthly Working Hours', 'group' => 'Reports', 'actions' => ['view']],
        ['key' => 'monthlyOtHoursReport', 'label' => 'Monthly OT Hours', 'group' => 'Reports', 'actions' => ['view']],
        ['key' => 'timeCardAuditReport', 'label' => 'Time Card Audit Report', 'group' => 'Reports', 'actions' => ['view']],
        ['key' => 'deletedTimeCardReport', 'label' => 'Deleted Time Card Report', 'group' => 'Reports', 'actions' => ['view']],
        ['key' => 'allowancesReport', 'label' => 'Allowances Report', 'group' => 'Reports', 'actions' => ['view']],
        ['key' => 'employeePortal', 'label' => 'Employee Portal', 'group' => 'Employee', 'actions' => ['view']],
        ['key' => 'myProfile', 'label' => 'My Profile', 'group' => 'Employee', 'actions' => ['view']],
        ['key' => 'changePassword', 'label' => 'Change Password', 'group' => 'Employee', 'actions' => ['view']],
        ['key' => 'salaryRecords', 'label' => 'Salary Records', 'group' => 'Employee', 'actions' => ['view']],
        ['key' => 'downloadSalarySlip', 'label' => 'Download Salary Slip', 'group' => 'Employee', 'actions' => ['view']],
    ],
];
