<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\inventory_product; // Using lowercase model name generated by artisan; consider renaming to InventoryProduct for PSR-4 compliance
use Illuminate\Support\Facades\Auth;

class InventoryProductController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        $perPage = min(max((int) $request->query('per_page', 15), 1), 100);

        return response()->json(
            inventory_product::latest()->paginate($perPage)
        );
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'cost' => ['required', 'numeric', 'min:0'],
            'quantity' => ['nullable', 'integer', 'min:0'],
            'min_price' => ['required', 'numeric', 'min:0'],
            'mrp' => ['required', 'numeric', 'min:0'],
            'amount' => ['required', 'numeric', 'min:0'],
            'product_id' => ['required', 'exists:products,id'],
            'inventory_id' => ['required', 'exists:inventories,id'],
            'created_by' => ['nullable', 'exists:users,id'],
        ]);

        $data = $validated;
        $creatorId = Auth::id() ?: ($data['created_by'] ?? null);
        if (!$creatorId) {
            return response()->json(['message' => 'created_by is required when not authenticated'], 422);
        }
        $data['created_by'] = $creatorId;

        // defaults
        $data['quantity'] = $data['quantity'] ?? 0;

        $product = inventory_product::create($data);

        return response()->json($product, 201);
    }

    /**
     * Display the specified resource.
     */
    public function show(inventory_product $inventoryProduct)
    {
        return response()->json($inventoryProduct);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, inventory_product $inventoryProduct)
    {
        $validated = $request->validate([
            'cost' => ['sometimes', 'required', 'numeric', 'min:0'],
            'quantity' => ['sometimes', 'nullable', 'integer', 'min:0'],
            'min_price' => ['sometimes', 'required', 'numeric', 'min:0'],
            'mrp' => ['sometimes', 'required', 'numeric', 'min:0'],
            'amount' => ['sometimes', 'required', 'numeric', 'min:0'],
            'product_id' => ['sometimes', 'required', 'exists:products,id'],
            'inventory_id' => ['sometimes', 'required', 'exists:inventories,id'],
        ]);

        $inventoryProduct->update($validated);
        return response()->json($inventoryProduct);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(inventory_product $inventoryProduct)
    {
        $inventoryProduct->delete();
        return response()->noContent();
    }
}
